# ---
# - name: Deploy AI Sensor Docker Container
#   hosts: localhost
#   become: yes  
#   tasks:
    - name: Login to Docker registry
      docker_login:
        username: 'robot-edgelabs-clients'
        password: 'LWb7bsa9msWphOy8brbXu6XJUlzXhfSV'
        registry_url: 'registry.edgelabs.ai'
      become: yes

    - name: Pull AI Sensor Docker image
      docker_image:
        name: 'registry.edgelabs.ai/ai-sensor/ai-sensor'
        tag: 'latest'
        source: pull
      become: yes

    - name: Manage AI Sensor Docker container
      docker_container:
        name: 'ai-sensor'
        image: 'registry.edgelabs.ai/ai-sensor/ai-sensor:latest'
        state: started
        restart_policy: always
        network_mode: 'host'
        capabilities:
          - 'NET_ADMIN'
        env:
          API_KEY: 'id1756317079|IWz602oCKaOuwBlhwEo8'
      become: yes

#TODO - update
# docker stop ai-sensor 
# docker rm ai-sensor 
# docker pull registry.edgelabs.ai/ai-sensor/ai-sensor:latest 
# or 
# docker pull registry.edgelabs.ai/ai-sensor/ai-sensor-arm:latest (for arm64) docker pull registry.edgelabs.ai/ai-sensor/ai-sensor-arm:latest (for multiplatform) 
# docker run … (from step 4 depending arch) 